# Generated by Django 4.2.5 on 2023-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditem_fats_per_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories_per_100g',
            field=models.FloatField(default=0, verbose_name='Calories/100g'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carb_per_100g',
            field=models.FloatField(default=0, verbose_name='Carb/100g'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fats_per_100g',
            field=models.FloatField(default=0, verbose_name='Fats/100g'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein_per_100g',
            field=models.FloatField(default=0, verbose_name='Protein/100g'),
        ),
    ]
